
import { type Element, type Evidence, EvidenceId, type Difficulty } from './types';

export const ALL_EVIDENCE: Evidence[] = [
  // --- Визуальный осмотр ---
  { id: EvidenceId.STATE_SOLID, name: "Визуальный осмотр", description: "Твёрдое тело при стандартных условиях." },
  { id: EvidenceId.STATE_GAS, name: "Визуальный осмотр", description: "Газ при стандартных условиях." },
  { id: EvidenceId.STATE_LIQUID, name: "Визуальный осмотр", description: "Жидкость при стандартных условиях." },
  { id: EvidenceId.COLOR_SILVERY, name: "Визуальный осмотр", description: "Имеет серебристо-белый или серый металлический блеск." },
  { id: EvidenceId.COLOR_YELLOW, name: "Визуальный осмотр", description: "Имеет характерный жёлтый цвет." },
  { id: EvidenceId.COLOR_REDDISH, name: "Визуальный осмотр", description: "Имеет красноватый или розоватый оттенок." },
  { id: EvidenceId.COLOR_BLACK, name: "Визуальный осмотр", description: "Чёрного или тёмно-серого цвета." },
  { id: EvidenceId.COLOR_YELLOW_GREEN_GAS, name: "Визуальный осмотр", description: "Газ жёлто-зелёного цвета." },
  { id: EvidenceId.COLOR_PALE_YELLOW_GAS, name: "Визуальный осмотр", description: "Газ бледно-жёлтого цвета." },
  { id: EvidenceId.COLOR_NONE, name: "Визуальный осмотр", description: "Образец бесцветен (для газов и жидкостей)." },

  // --- Классификация ---
  { id: EvidenceId.TYPE_METAL, name: "Классификация", description: "Определён как металл." },
  { id: EvidenceId.TYPE_NONMETAL, name: "Классификация", description: "Определён как неметалл." },
  { id: EvidenceId.TYPE_METALLOID, name: "Классификация", description: "Определён как металлоид (полуметалл)." },

  // --- Спектральный анализ (Категории) ---
  { id: EvidenceId.CATEGORY_ALKALI_METAL, name: "Спектральный анализ", description: "Определён как щелочной металл." },
  { id: EvidenceId.CATEGORY_ALKALINE_EARTH_METAL, name: "Спектральный анализ", description: "Определён как щёлочноземельный металл." },
  { id: EvidenceId.CATEGORY_TRANSITION_METAL, name: "Спектральный анализ", description: "Определён как переходный металл." },
  { id: EvidenceId.CATEGORY_POST_TRANSITION_METAL, name: "Спектральный анализ", description: "Определён как постпереходный металл." },
  { id: EvidenceId.CATEGORY_LANTHANIDE, name: "Спектральный анализ", description: "Определён как лантаноид." },
  { id: EvidenceId.CATEGORY_ACTINIDE, name: "Спектральный анализ", description: "Определён как актиноид." },
  { id: EvidenceId.CATEGORY_METALLOID, name: "Спектральный анализ", description: "Определён как металлоид." },
  { id: EvidenceId.CATEGORY_OTHER_NONMETAL, name: "Спектральный анализ", description: "Определён как прочий неметалл." },
  { id: EvidenceId.CATEGORY_HALOGEN, name: "Спектральный анализ", description: "Определён как галоген." },
  { id: EvidenceId.CATEGORY_NOBLE_GAS, name: "Спектральный анализ", description: "Определён как благородный газ." },

  // --- Пламенный тест ---
  { id: EvidenceId.FLAME_ORANGE, name: "Пламенный тест", description: "Пламя оранжевое или оранжево-красное." },
  { id: EvidenceId.FLAME_GREEN, name: "Пламенный тест", description: "Пламя ярко-зелёное." },
  { id: EvidenceId.FLAME_PALE_GREEN, name: "Пламенный тест", description: "Пламя бледно-зелёное." },
  { id: EvidenceId.FLAME_RED, name: "Пламенный тест", description: "Пламя красное или малиновое." },
  { id: EvidenceId.FLAME_LILAC, name: "Пламенный тест", description: "Пламя сиреневое (бледно-фиолетовое)." },
  { id: EvidenceId.FLAME_YELLOW_GREEN, name: "Пламенный тест", description: "Пламя жёлто-зелёное." },
  { id: EvidenceId.FLAME_BLUE, name: "Пламенный тест", description: "Пламя синее или бледно-голубое." },
  { id: EvidenceId.FLAME_YELLOW, name: "Пламенный тест", description: "Пламя ярко-жёлтое." },
  { id: EvidenceId.FLAME_NONE, name: "Пламенный тест", description: "Образец не окрашивает пламя." },

  // --- Тест на амфотерность ---
  { id: EvidenceId.AMPHOTERIC, name: "Тест на амфотерность", description: "Проявляет амфотерные свойства (реагирует с кислотами и щелочами)." },
  { id: EvidenceId.NOT_AMPHOTERIC, name: "Тест на амфотерность", description: "Не проявляет амфотерных свойств." },

  // --- Тест на проводимость ---
  { id: EvidenceId.CONDUCTIVE, name: "Тест на проводимость", description: "Проводит электричество." },
  { id: EvidenceId.NOT_CONDUCTIVE, name: "Тест на проводимость", description: "Не проводит электричество (является изолятором)." },

  // --- Счётчик Гейгера ---
  { id: EvidenceId.RADIOACTIVE, name: "Счётчик Гейгера", description: "Излучает ионизирующую радиацию." },
  { id: EvidenceId.NOT_RADIOACTIVE, name: "Счётчик Гейгера", description: "Радиоактивность не обнаружена." },

  // --- Тест на магнетизм ---
  { id: EvidenceId.MAGNETIC_FERRO, name: "Тест на магнетизм", description: "Образец сильно притягивается к магниту (ферромагнетик)." },
  { id: EvidenceId.MAGNETIC_PARAM, name: "Тест на магнетизм", description: "Образец слабо притягивается к магниту (парамагнетик)." },
  { id: EvidenceId.MAGNETIC_DIA, name: "Тест на магнетизм", description: "Образец слабо отталкивается от магнита (диамагнетик)." },

  // --- Реакция с водой ---
  { id: EvidenceId.REACTS_WATER_EXPLOSIVELY, name: "Реакция с водой", description: "Взрывная реакция с водой со вспышкой." },
  { id: EvidenceId.REACTS_WATER_VIOLENTLY, name: "Реакция с водой", description: "Бурная реакция с водой с выделением газа." },
  { id: EvidenceId.REACTS_WATER_SLOWLY, name: "Реакция с водой", description: "Медленная или умеренная реакция с водой." },
  { id: EvidenceId.NO_REACTION_WATER, name: "Реакция с водой", description: "Нет видимой реакции с холодной водой." },

  // --- Реакция с AgNO₃ ---
  { id: EvidenceId.PRECIPITATE_WHITE, name: "Реакция с AgNO₃", description: "Образуется белый творожистый осадок." },
  { id: EvidenceId.PRECIPITATE_CREAM, name: "Реакция с AgNO₃", description: "Образуется бледно-жёлтый (кремовый) осадок." },
  { id: EvidenceId.PRECIPITATE_YELLOW, name: "Реакция с AgNO₃", description: "Образуется жёлтый осадок." },
  { id: EvidenceId.NO_PRECIPITATE, name: "Реакция с AgNO₃", description: "Осадок не образуется." },

  // --- Тест на горючесть ---
  { id: EvidenceId.COMBUSTIBLE_GAS_FLAMMABLE, name: "Тест на горючесть", description: "Газ воспламеняется с характерным звуком." },
  { id: EvidenceId.COMBUSTIBLE_GAS_SUPPORTS, name: "Тест на горючесть", description: "Газ активно поддерживает горение (тлеющая лучинка вспыхивает)." },
  { id: EvidenceId.COMBUSTIBLE_SOLID, name: "Тест на горючесть", description: "Твёрдое вещество горит на воздухе." },
  { id: EvidenceId.NOT_COMBUSTIBLE, name: "Тест на горючесть", description: "Образец не горит и не поддерживает горение." },

  // --- Реакция с кислотой ---
  { id: EvidenceId.REACTS_HCL, name: "Реакция с кислотой", description: "Реагирует с соляной кислотой с выделением газа." },
  { id: EvidenceId.NO_REACTION_HCL, name: "Реакция с кислотой", description: "Не реагирует с соляной кислотой." },

  // --- Измерение плотности ---
  { id: EvidenceId.DENSITY_HIGH, name: "Измерение плотности", description: "Высокая плотность (> 10 г/см³)." },
  { id: EvidenceId.DENSITY_MEDIUM, name: "Измерение плотности", description: "Средняя плотность (5-10 г/см³)." },
  { id: EvidenceId.DENSITY_LOW, name: "Измерение плотности", description: "Низкая плотность (< 5 г/см³)." },

  // --- Анализ запаха ---
  { id: EvidenceId.SMELL_PUNGENT, name: "Анализ запаха", description: "Обладает резким, характерным запахом." },
  { id: EvidenceId.SMELL_NONE, name: "Анализ запаха", description: "Не имеет запаха." },
  
  // --- Температура плавления ---
  { id: EvidenceId.MELTS_IN_HAND, name: "Температура плавления", description: "Образец плавится от тепла руки (t°пл < 30°C)." },
  { id: EvidenceId.MP_HIGH, name: "Температура плавления", description: "Температура плавления значительно выше комнатной." },
  { id: EvidenceId.MP_VERY_LOW, name: "Температура плавления", description: "Температура плавления значительно ниже комнатной." },
];

export const EVIDENCE_MAP: Map<EvidenceId, Evidence> = new Map(ALL_EVIDENCE.map(e => [e.id, e]));

export const AVAILABLE_TESTS: Evidence[] = [
    { id: EvidenceId.STATE_SOLID, name: "Визуальный осмотр", description: "Определяет состояние и цвет образца." },
    { id: EvidenceId.TYPE_METAL, name: "Классификация", description: "Определяет тип вещества (металл/неметалл)." },
    { id: EvidenceId.CATEGORY_ALKALI_METAL, name: "Спектральный анализ", description: "Определяет химическую группу элемента." },
    { id: EvidenceId.CONDUCTIVE, name: "Тест на проводимость", description: "Проверяет способность проводить ток." },
    { id: EvidenceId.FLAME_ORANGE, name: "Пламенный тест", description: "Проверяет цвет пламени." },
    { id: EvidenceId.REACTS_WATER_VIOLENTLY, name: "Реакция с водой", description: "Проверяет химическую активность в воде." },
    { id: EvidenceId.REACTS_HCL, name: "Реакция с кислотой", description: "Проверяет реакцию с соляной кислотой (HCl)." },
    { id: EvidenceId.MAGNETIC_FERRO, name: "Тест на магнетизм", description: "Проверяет магнитные свойства." },
    { id: EvidenceId.DENSITY_HIGH, name: "Измерение плотности", description: "Определяет примерную плотность." },
    { id: EvidenceId.AMPHOTERIC, name: "Тест на амфотерность", description: "Проверяет реакцию со щелочами." },
    { id: EvidenceId.COMBUSTIBLE_SOLID, name: "Тест на горючесть", description: "Проверяет способность гореть." },
    { id: EvidenceId.SMELL_PUNGENT, name: "Анализ запаха", description: "Проверяет наличие запаха." },
    { id: EvidenceId.RADIOACTIVE, name: "Счётчик Гейгера", description: "Обнаруживает радиацию." },
    { id: EvidenceId.PRECIPITATE_WHITE, name: "Реакция с AgNO₃", description: "Проверяет наличие галогенид-ионов." },
    { id: EvidenceId.MELTS_IN_HAND, name: "Температура плавления", description: "Проверяет, плавится ли при низкой температуре." },
];

export const CATEGORY_COLORS: Record<string, string> = {
  'alkali-metal': 'bg-red-700 hover:bg-red-600 border-red-500',
  'alkaline-earth-metal': 'bg-orange-600 hover:bg-orange-500 border-orange-400',
  'transition-metal': 'bg-yellow-600 hover:bg-yellow-500 border-yellow-400',
  'post-transition-metal': 'bg-green-600 hover:bg-green-500 border-green-400',
  'lanthanide': 'bg-teal-700 hover:bg-teal-600 border-teal-500',
  'actinide': 'bg-purple-700 hover:bg-purple-600 border-purple-500',
  'metalloid': 'bg-cyan-600 hover:bg-cyan-500 border-cyan-400',
  'other-nonmetal': 'bg-blue-600 hover:bg-blue-500 border-blue-400',
  'halogen': 'bg-indigo-600 hover:bg-indigo-500 border-indigo-400',
  'noble-gas': 'bg-pink-800 hover:bg-pink-700 border-pink-600',
  'default': 'bg-slate-700 hover:bg-slate-600 border-slate-500',
};

const fullElementList: Element[] = [
    // --- Period 1 ---
    { name: 'Водород', symbol: 'H', atomicNumber: 1, atomicMass: 1.008, category: 'other-nonmetal', properties: [EvidenceId.STATE_GAS, EvidenceId.COLOR_NONE, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_PRECIPITATE, EvidenceId.COMBUSTIBLE_GAS_FLAMMABLE, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.SMELL_NONE, EvidenceId.MP_VERY_LOW, EvidenceId.FLAME_BLUE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_OTHER_NONMETAL], period: 1, group: 1 },
    { name: 'Гелий', symbol: 'He', atomicNumber: 2, atomicMass: 4.0026, category: 'noble-gas', properties: [EvidenceId.STATE_GAS, EvidenceId.COLOR_NONE, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.SMELL_NONE, EvidenceId.MP_VERY_LOW, EvidenceId.FLAME_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_NOBLE_GAS], period: 1, group: 18 },
    // --- Period 2 ---
    { name: 'Литий', symbol: 'Li', atomicNumber: 3, atomicMass: 6.94, category: 'alkali-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_RED, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_VIOLENTLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ALKALI_METAL], period: 2, group: 1 },
    { name: 'Бериллий', symbol: 'Be', atomicNumber: 4, atomicMass: 9.0122, category: 'alkaline-earth-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.AMPHOTERIC, EvidenceId.CATEGORY_ALKALINE_EARTH_METAL], period: 2, group: 2 },
    { name: 'Бор', symbol: 'B', atomicNumber: 5, atomicMass: 10.81, category: 'metalloid', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_BLACK, EvidenceId.TYPE_METALLOID, EvidenceId.NOT_CONDUCTIVE, EvidenceId.FLAME_GREEN, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_METALLOID], period: 2, group: 13 },
    { name: 'Углерод', symbol: 'C', atomicNumber: 6, atomicMass: 12.011, category: 'other-nonmetal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_BLACK, EvidenceId.TYPE_NONMETAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.COMBUSTIBLE_SOLID, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_OTHER_NONMETAL], period: 2, group: 14 },
    { name: 'Азот', symbol: 'N', atomicNumber: 7, atomicMass: 14.007, category: 'other-nonmetal', properties: [EvidenceId.STATE_GAS, EvidenceId.COLOR_NONE, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.SMELL_NONE, EvidenceId.MP_VERY_LOW, EvidenceId.FLAME_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_OTHER_NONMETAL], period: 2, group: 15 },
    { name: 'Кислород', symbol: 'O', atomicNumber: 8, atomicMass: 15.999, category: 'other-nonmetal', properties: [EvidenceId.STATE_GAS, EvidenceId.COLOR_NONE, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_PRECIPITATE, EvidenceId.COMBUSTIBLE_GAS_SUPPORTS, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.SMELL_NONE, EvidenceId.MP_VERY_LOW, EvidenceId.FLAME_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_OTHER_NONMETAL], period: 2, group: 16 },
    { name: 'Фтор', symbol: 'F', atomicNumber: 9, atomicMass: 18.998, category: 'halogen', properties: [EvidenceId.STATE_GAS, EvidenceId.COLOR_PALE_YELLOW_GAS, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.REACTS_WATER_VIOLENTLY, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.SMELL_PUNGENT, EvidenceId.MP_VERY_LOW, EvidenceId.FLAME_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_HALOGEN], period: 2, group: 17 },
    { name: 'Неон', symbol: 'Ne', atomicNumber: 10, atomicMass: 20.180, category: 'noble-gas', properties: [EvidenceId.STATE_GAS, EvidenceId.COLOR_NONE, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.SMELL_NONE, EvidenceId.MP_VERY_LOW, EvidenceId.FLAME_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_NOBLE_GAS], period: 2, group: 18 },
    // --- Period 3 ---
    { name: 'Натрий', symbol: 'Na', atomicNumber: 11, atomicMass: 22.990, category: 'alkali-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_YELLOW, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_VIOLENTLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ALKALI_METAL], period: 3, group: 1 },
    { name: 'Магний', symbol: 'Mg', atomicNumber: 12, atomicMass: 24.305, category: 'alkaline-earth-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ALKALINE_EARTH_METAL], period: 3, group: 2 },
    { name: 'Алюминий', symbol: 'Al', atomicNumber: 13, atomicMass: 26.982, category: 'post-transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.AMPHOTERIC, EvidenceId.CATEGORY_POST_TRANSITION_METAL], period: 3, group: 13 },
    { name: 'Кремний', symbol: 'Si', atomicNumber: 14, atomicMass: 28.085, category: 'metalloid', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METALLOID, EvidenceId.NOT_CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_METALLOID], period: 3, group: 14 },
    { name: 'Фосфор', symbol: 'P', atomicNumber: 15, atomicMass: 30.974, category: 'other-nonmetal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_BLACK, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.FLAME_PALE_GREEN, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.COMBUSTIBLE_SOLID, EvidenceId.SMELL_PUNGENT, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_OTHER_NONMETAL], period: 3, group: 15 },
    { name: 'Сера', symbol: 'S', atomicNumber: 16, atomicMass: 32.06, category: 'other-nonmetal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_YELLOW, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.FLAME_BLUE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.COMBUSTIBLE_SOLID, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_OTHER_NONMETAL], period: 3, group: 16 },
    { name: 'Хлор', symbol: 'Cl', atomicNumber: 17, atomicMass: 35.45, category: 'halogen', properties: [EvidenceId.STATE_GAS, EvidenceId.COLOR_YELLOW_GREEN_GAS, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.PRECIPITATE_WHITE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.SMELL_PUNGENT, EvidenceId.MP_VERY_LOW, EvidenceId.FLAME_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_HALOGEN], period: 3, group: 17 },
    { name: 'Аргон', symbol: 'Ar', atomicNumber: 18, atomicMass: 39.948, category: 'noble-gas', properties: [EvidenceId.STATE_GAS, EvidenceId.COLOR_NONE, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.SMELL_NONE, EvidenceId.MP_VERY_LOW, EvidenceId.FLAME_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_NOBLE_GAS], period: 3, group: 18 },
    // --- Period 4 ---
    { name: 'Калий', symbol: 'K', atomicNumber: 19, atomicMass: 39.098, category: 'alkali-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_LILAC, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_VIOLENTLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ALKALI_METAL], period: 4, group: 1 },
    { name: 'Кальций', symbol: 'Ca', atomicNumber: 20, atomicMass: 40.078, category: 'alkaline-earth-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_ORANGE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ALKALINE_EARTH_METAL], period: 4, group: 2 },
    { name: 'Скандий', symbol: 'Sc', atomicNumber: 21, atomicMass: 44.956, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 4, group: 3 },
    { name: 'Титан', symbol: 'Ti', atomicNumber: 22, atomicMass: 47.867, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 4, group: 4 },
    { name: 'Ванадий', symbol: 'V', atomicNumber: 23, atomicMass: 50.942, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 4, group: 5 },
    { name: 'Хром', symbol: 'Cr', atomicNumber: 24, atomicMass: 51.996, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 4, group: 6 },
    { name: 'Марганец', symbol: 'Mn', atomicNumber: 25, atomicMass: 54.938, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 4, group: 7 },
    { name: 'Железо', symbol: 'Fe', atomicNumber: 26, atomicMass: 55.845, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_FERRO, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 4, group: 8 },
    { name: 'Кобальт', symbol: 'Co', atomicNumber: 27, atomicMass: 58.933, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_FERRO, EvidenceId.NO_REACTION_WATER, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 4, group: 9 },
    { name: 'Никель', symbol: 'Ni', atomicNumber: 28, atomicMass: 58.693, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_FERRO, EvidenceId.NO_REACTION_WATER, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 4, group: 10 },
    { name: 'Медь', symbol: 'Cu', atomicNumber: 29, atomicMass: 63.546, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_REDDISH, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_GREEN, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 4, group: 11 },
    { name: 'Цинк', symbol: 'Zn', atomicNumber: 30, atomicMass: 65.38, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_BLUE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 4, group: 12 },
    { name: 'Галлий', symbol: 'Ga', atomicNumber: 31, atomicMass: 69.723, category: 'post-transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MELTS_IN_HAND, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.AMPHOTERIC, EvidenceId.CATEGORY_POST_TRANSITION_METAL], period: 4, group: 13 },
    { name: 'Германий', symbol: 'Ge', atomicNumber: 32, atomicMass: 72.630, category: 'metalloid', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METALLOID, EvidenceId.NOT_CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.AMPHOTERIC, EvidenceId.CATEGORY_METALLOID], period: 4, group: 14 },
    { name: 'Мышьяк', symbol: 'As', atomicNumber: 33, atomicMass: 74.922, category: 'metalloid', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METALLOID, EvidenceId.NOT_CONDUCTIVE, EvidenceId.FLAME_BLUE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_PUNGENT, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_METALLOID], period: 4, group: 15 },
    { name: 'Селен', symbol: 'Se', atomicNumber: 34, atomicMass: 78.971, category: 'other-nonmetal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_BLACK, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.FLAME_BLUE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.COMBUSTIBLE_SOLID, EvidenceId.SMELL_PUNGENT, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_OTHER_NONMETAL], period: 4, group: 16 },
    { name: 'Бром', symbol: 'Br', atomicNumber: 35, atomicMass: 79.904, category: 'halogen', properties: [EvidenceId.STATE_LIQUID, EvidenceId.COLOR_REDDISH, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.PRECIPITATE_CREAM, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.SMELL_PUNGENT, EvidenceId.MP_VERY_LOW, EvidenceId.FLAME_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_HALOGEN], period: 4, group: 17 },
    { name: 'Криптон', symbol: 'Kr', atomicNumber: 36, atomicMass: 83.798, category: 'noble-gas', properties: [EvidenceId.STATE_GAS, EvidenceId.COLOR_NONE, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.SMELL_NONE, EvidenceId.MP_VERY_LOW, EvidenceId.FLAME_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_NOBLE_GAS], period: 4, group: 18 },
    // --- Period 5 ---
    { name: 'Рубидий', symbol: 'Rb', atomicNumber: 37, atomicMass: 85.468, category: 'alkali-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_LILAC, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_EXPLOSIVELY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ALKALI_METAL], period: 5, group: 1 },
    { name: 'Стронций', symbol: 'Sr', atomicNumber: 38, atomicMass: 87.62, category: 'alkaline-earth-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_RED, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_VIOLENTLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ALKALINE_EARTH_METAL], period: 5, group: 2 },
    { name: 'Иттрий', symbol: 'Y', atomicNumber: 39, atomicMass: 88.906, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 5, group: 3 },
    { name: 'Цирконий', symbol: 'Zr', atomicNumber: 40, atomicMass: 91.224, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 5, group: 4 },
    { name: 'Ниобий', symbol: 'Nb', atomicNumber: 41, atomicMass: 92.906, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 5, group: 5 },
    { name: 'Молибден', symbol: 'Mo', atomicNumber: 42, atomicMass: 95.96, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 5, group: 6 },
    { name: 'Технеций', symbol: 'Tc', atomicNumber: 43, atomicMass: 98, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 5, group: 7 },
    { name: 'Рутений', symbol: 'Ru', atomicNumber: 44, atomicMass: 101.07, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 5, group: 8 },
    { name: 'Родий', symbol: 'Rh', atomicNumber: 45, atomicMass: 102.91, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 5, group: 9 },
    { name: 'Палладий', symbol: 'Pd', atomicNumber: 46, atomicMass: 106.42, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 5, group: 10 },
    { name: 'Серебро', symbol: 'Ag', atomicNumber: 47, atomicMass: 107.87, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 5, group: 11 },
    { name: 'Кадмий', symbol: 'Cd', atomicNumber: 48, atomicMass: 112.41, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 5, group: 12 },
    { name: 'Индий', symbol: 'In', atomicNumber: 49, atomicMass: 114.82, category: 'post-transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_BLUE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.AMPHOTERIC, EvidenceId.CATEGORY_POST_TRANSITION_METAL], period: 5, group: 13 },
    { name: 'Олово', symbol: 'Sn', atomicNumber: 50, atomicMass: 118.71, category: 'post-transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.AMPHOTERIC, EvidenceId.CATEGORY_POST_TRANSITION_METAL], period: 5, group: 14 },
    { name: 'Сурьма', symbol: 'Sb', atomicNumber: 51, atomicMass: 121.76, category: 'metalloid', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METALLOID, EvidenceId.NOT_CONDUCTIVE, EvidenceId.FLAME_PALE_GREEN, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.AMPHOTERIC, EvidenceId.CATEGORY_METALLOID], period: 5, group: 15 },
    { name: 'Теллур', symbol: 'Te', atomicNumber: 52, atomicMass: 127.60, category: 'metalloid', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METALLOID, EvidenceId.NOT_CONDUCTIVE, EvidenceId.FLAME_GREEN, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_METALLOID], period: 5, group: 16 },
    { name: 'Иод', symbol: 'I', atomicNumber: 53, atomicMass: 126.90, category: 'halogen', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_BLACK, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.PRECIPITATE_YELLOW, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.SMELL_PUNGENT, EvidenceId.MP_HIGH, EvidenceId.FLAME_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_HALOGEN], period: 5, group: 17 },
    { name: 'Ксенон', symbol: 'Xe', atomicNumber: 54, atomicMass: 131.29, category: 'noble-gas', properties: [EvidenceId.STATE_GAS, EvidenceId.COLOR_NONE, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_LOW, EvidenceId.SMELL_NONE, EvidenceId.MP_VERY_LOW, EvidenceId.FLAME_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_NOBLE_GAS], period: 5, group: 18 },
    // --- Period 6 ---
    { name: 'Цезий', symbol: 'Cs', atomicNumber: 55, atomicMass: 132.91, category: 'alkali-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_BLUE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_EXPLOSIVELY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MELTS_IN_HAND, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ALKALI_METAL], period: 6, group: 1 },
    { name: 'Барий', symbol: 'Ba', atomicNumber: 56, atomicMass: 137.33, category: 'alkaline-earth-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_YELLOW_GREEN, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_VIOLENTLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ALKALINE_EARTH_METAL], period: 6, group: 2 },
    { name: 'Лантан', symbol: 'La', atomicNumber: 57, atomicMass: 138.91, category: 'lanthanide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_LANTHANIDE], period: 6, group: 3 },
    { name: 'Церий', symbol: 'Ce', atomicNumber: 58, atomicMass: 140.12, category: 'lanthanide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_LANTHANIDE], period: 6, group: 3 },
    { name: 'Празеодим', symbol: 'Pr', atomicNumber: 59, atomicMass: 140.91, category: 'lanthanide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_LANTHANIDE], period: 6, group: 3 },
    { name: 'Неодим', symbol: 'Nd', atomicNumber: 60, atomicMass: 144.24, category: 'lanthanide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_LANTHANIDE], period: 6, group: 3 },
    { name: 'Прометий', symbol: 'Pm', atomicNumber: 61, atomicMass: 145, category: 'lanthanide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_LANTHANIDE], period: 6, group: 3 },
    { name: 'Самарий', symbol: 'Sm', atomicNumber: 62, atomicMass: 150.36, category: 'lanthanide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_LANTHANIDE], period: 6, group: 3 },
    { name: 'Европий', symbol: 'Eu', atomicNumber: 63, atomicMass: 151.96, category: 'lanthanide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_VIOLENTLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_LANTHANIDE], period: 6, group: 3 },
    { name: 'Гадолиний', symbol: 'Gd', atomicNumber: 64, atomicMass: 157.25, category: 'lanthanide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_FERRO, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_LANTHANIDE], period: 6, group: 3 },
    { name: 'Тербий', symbol: 'Tb', atomicNumber: 65, atomicMass: 158.93, category: 'lanthanide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_FERRO, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_LANTHANIDE], period: 6, group: 3 },
    { name: 'Диспрозий', symbol: 'Dy', atomicNumber: 66, atomicMass: 162.50, category: 'lanthanide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_FERRO, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_LANTHANIDE], period: 6, group: 3 },
    { name: 'Гольмий', symbol: 'Ho', atomicNumber: 67, atomicMass: 164.93, category: 'lanthanide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_FERRO, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_LANTHANIDE], period: 6, group: 3 },
    { name: 'Эрбий', symbol: 'Er', atomicNumber: 68, atomicMass: 167.26, category: 'lanthanide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_FERRO, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_LANTHANIDE], period: 6, group: 3 },
    { name: 'Тулий', symbol: 'Tm', atomicNumber: 69, atomicMass: 168.93, category: 'lanthanide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_FERRO, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_LANTHANIDE], period: 6, group: 3 },
    { name: 'Иттербий', symbol: 'Yb', atomicNumber: 70, atomicMass: 173.05, category: 'lanthanide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_LANTHANIDE], period: 6, group: 3 },
    { name: 'Лютеций', symbol: 'Lu', atomicNumber: 71, atomicMass: 174.97, category: 'lanthanide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_LANTHANIDE], period: 6, group: 3 },
    { name: 'Гафний', symbol: 'Hf', atomicNumber: 72, atomicMass: 178.49, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 6, group: 4 },
    { name: 'Тантал', symbol: 'Ta', atomicNumber: 73, atomicMass: 180.95, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 6, group: 5 },
    { name: 'Вольфрам', symbol: 'W', atomicNumber: 74, atomicMass: 183.84, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 6, group: 6 },
    { name: 'Рений', symbol: 'Re', atomicNumber: 75, atomicMass: 186.21, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 6, group: 7 },
    { name: 'Осмий', symbol: 'Os', atomicNumber: 76, atomicMass: 190.23, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 6, group: 8 },
    { name: 'Иридий', symbol: 'Ir', atomicNumber: 77, atomicMass: 192.22, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 6, group: 9 },
    { name: 'Платина', symbol: 'Pt', atomicNumber: 78, atomicMass: 195.08, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 6, group: 10 },
    { name: 'Золото', symbol: 'Au', atomicNumber: 79, atomicMass: 196.97, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_YELLOW, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 6, group: 11 },
    { name: 'Ртуть', symbol: 'Hg', atomicNumber: 80, atomicMass: 200.59, category: 'transition-metal', properties: [EvidenceId.STATE_LIQUID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_VERY_LOW, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 6, group: 12 },
    { name: 'Таллий', symbol: 'Tl', atomicNumber: 81, atomicMass: 204.38, category: 'post-transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_GREEN, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_POST_TRANSITION_METAL], period: 6, group: 13 },
    { name: 'Свинец', symbol: 'Pb', atomicNumber: 82, atomicMass: 207.2, category: 'post-transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.AMPHOTERIC, EvidenceId.CATEGORY_POST_TRANSITION_METAL], period: 6, group: 14 },
    { name: 'Висмут', symbol: 'Bi', atomicNumber: 83, atomicMass: 208.98, category: 'post-transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.NOT_RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_POST_TRANSITION_METAL], period: 6, group: 15 },
    { name: 'Полоний', symbol: 'Po', atomicNumber: 84, atomicMass: 209, category: 'metalloid', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METALLOID, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.AMPHOTERIC, EvidenceId.CATEGORY_METALLOID], period: 6, group: 16 },
    { name: 'Астат', symbol: 'At', atomicNumber: 85, atomicMass: 210, category: 'halogen', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_BLACK, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.SMELL_NONE, EvidenceId.MP_HIGH, EvidenceId.FLAME_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_HALOGEN], period: 6, group: 17 },
    { name: 'Радон', symbol: 'Rn', atomicNumber: 86, atomicMass: 222, category: 'noble-gas', properties: [EvidenceId.STATE_GAS, EvidenceId.COLOR_NONE, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_DIA, EvidenceId.NO_REACTION_WATER, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.NO_REACTION_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.SMELL_NONE, EvidenceId.MP_VERY_LOW, EvidenceId.FLAME_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_NOBLE_GAS], period: 6, group: 18 },
    // --- Period 7 ---
    { name: 'Франций', symbol: 'Fr', atomicNumber: 87, atomicMass: 223, category: 'alkali-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_EXPLOSIVELY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_LOW, EvidenceId.MELTS_IN_HAND, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ALKALI_METAL], period: 7, group: 1 },
    { name: 'Радий', symbol: 'Ra', atomicNumber: 88, atomicMass: 226, category: 'alkaline-earth-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_RED, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_VIOLENTLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_MEDIUM, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ALKALINE_EARTH_METAL], period: 7, group: 2 },
    { name: 'Актиний', symbol: 'Ac', atomicNumber: 89, atomicMass: 227, category: 'actinide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ACTINIDE], period: 7, group: 3 },
    { name: 'Торий', symbol: 'Th', atomicNumber: 90, atomicMass: 232.04, category: 'actinide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ACTINIDE], period: 7, group: 3 },
    { name: 'Протактиний', symbol: 'Pa', atomicNumber: 91, atomicMass: 231.04, category: 'actinide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ACTINIDE], period: 7, group: 3 },
    { name: 'Уран', symbol: 'U', atomicNumber: 92, atomicMass: 238.03, category: 'actinide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ACTINIDE], period: 7, group: 3 },
    { name: 'Нептуний', symbol: 'Np', atomicNumber: 93, atomicMass: 237, category: 'actinide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ACTINIDE], period: 7, group: 3 },
    { name: 'Плутоний', symbol: 'Pu', atomicNumber: 94, atomicMass: 244, category: 'actinide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ACTINIDE], period: 7, group: 3 },
    { name: 'Америций', symbol: 'Am', atomicNumber: 95, atomicMass: 243, category: 'actinide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ACTINIDE], period: 7, group: 3 },
    { name: 'Кюрий', symbol: 'Cm', atomicNumber: 96, atomicMass: 247, category: 'actinide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ACTINIDE], period: 7, group: 3 },
    { name: 'Берклий', symbol: 'Bk', atomicNumber: 97, atomicMass: 247, category: 'actinide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ACTINIDE], period: 7, group: 3 },
    { name: 'Калифорний', symbol: 'Cf', atomicNumber: 98, atomicMass: 251, category: 'actinide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ACTINIDE], period: 7, group: 3 },
    { name: 'Эйнштейний', symbol: 'Es', atomicNumber: 99, atomicMass: 252, category: 'actinide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ACTINIDE], period: 7, group: 3 },
    { name: 'Фермий', symbol: 'Fm', atomicNumber: 100, atomicMass: 257, category: 'actinide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ACTINIDE], period: 7, group: 3 },
    { name: 'Менделевий', symbol: 'Md', atomicNumber: 101, atomicMass: 258, category: 'actinide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ACTINIDE], period: 7, group: 3 },
    { name: 'Нобелий', symbol: 'No', atomicNumber: 102, atomicMass: 259, category: 'actinide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ACTINIDE], period: 7, group: 3 },
    { name: 'Лоуренсий', symbol: 'Lr', atomicNumber: 103, atomicMass: 262, category: 'actinide', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_ACTINIDE], period: 7, group: 3 },
    { name: 'Резерфордий', symbol: 'Rf', atomicNumber: 104, atomicMass: 267, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 7, group: 4 },
    { name: 'Дубний', symbol: 'Db', atomicNumber: 105, atomicMass: 268, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 7, group: 5 },
    { name: 'Сиборгий', symbol: 'Sg', atomicNumber: 106, atomicMass: 271, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 7, group: 6 },
    { name: 'Борий', symbol: 'Bh', atomicNumber: 107, atomicMass: 272, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 7, group: 7 },
    { name: 'Хассий', symbol: 'Hs', atomicNumber: 108, atomicMass: 277, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 7, group: 8 },
    { name: 'Мейтнерий', symbol: 'Mt', atomicNumber: 109, atomicMass: 276, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 7, group: 9 },
    { name: 'Дармштадтий', symbol: 'Ds', atomicNumber: 110, atomicMass: 281, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 7, group: 10 },
    { name: 'Рентгений', symbol: 'Rg', atomicNumber: 111, atomicMass: 280, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 7, group: 11 },
    { name: 'Коперниций', symbol: 'Cn', atomicNumber: 112, atomicMass: 285, category: 'transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_TRANSITION_METAL], period: 7, group: 12 },
    { name: 'Нихоний', symbol: 'Nh', atomicNumber: 113, atomicMass: 284, category: 'post-transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_POST_TRANSITION_METAL], period: 7, group: 13 },
    { name: 'Флеровий', symbol: 'Fl', atomicNumber: 114, atomicMass: 289, category: 'post-transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_POST_TRANSITION_METAL], period: 7, group: 14 },
    { name: 'Московий', symbol: 'Mc', atomicNumber: 115, atomicMass: 288, category: 'post-transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_POST_TRANSITION_METAL], period: 7, group: 15 },
    { name: 'Ливерморий', symbol: 'Lv', atomicNumber: 116, atomicMass: 293, category: 'post-transition-metal', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_SILVERY, EvidenceId.TYPE_METAL, EvidenceId.CONDUCTIVE, EvidenceId.FLAME_NONE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_POST_TRANSITION_METAL], period: 7, group: 16 },
    { name: 'Теннессин', symbol: 'Ts', atomicNumber: 117, atomicMass: 294, category: 'halogen', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_BLACK, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_HALOGEN], period: 7, group: 17 },
    { name: 'Оганесон', symbol: 'Og', atomicNumber: 118, atomicMass: 294, category: 'noble-gas', properties: [EvidenceId.STATE_SOLID, EvidenceId.COLOR_NONE, EvidenceId.TYPE_NONMETAL, EvidenceId.NOT_CONDUCTIVE, EvidenceId.RADIOACTIVE, EvidenceId.MAGNETIC_PARAM, EvidenceId.REACTS_WATER_SLOWLY, EvidenceId.REACTS_HCL, EvidenceId.DENSITY_HIGH, EvidenceId.MP_HIGH, EvidenceId.NO_PRECIPITATE, EvidenceId.NOT_COMBUSTIBLE, EvidenceId.SMELL_NONE, EvidenceId.NOT_AMPHOTERIC, EvidenceId.CATEGORY_NOBLE_GAS], period: 7, group: 18 },
];

export const ELEMENTS: Element[] = [...fullElementList];

const EASY_ELEMENTS = fullElementList.filter(el => [
    'H', 'He', 'Li', 'C', 'N', 'O', 'F', 'Ne', 'Na', 'Mg', 'Al', 'Si', 'P', 'S', 'Cl', 'Ar',
    'K', 'Ca', 'Fe', 'Ni', 'Cu', 'Zn', 'Ag', 'I', 'Au', 'Hg', 'Pb'
].includes(el.symbol));

const MEDIUM_ELEMENTS = fullElementList.filter(el => el.atomicNumber <= 54);

const HARD_ELEMENTS = fullElementList.filter(el => el.atomicNumber <= 92);

const EXPERT_ELEMENTS = fullElementList;

interface DifficultySetting {
    name: string;
    description: string;
    uses: number;
    elementPool: Element[];
}

export const DIFFICULTY_SETTINGS: Record<Difficulty, DifficultySetting> = {
    beginner: {
        name: "Новичок",
        description: "Основы химии. Простые элементы и неограниченное количество тестов для спокойного изучения.",
        uses: 999,
        elementPool: EASY_ELEMENTS,
    },
    apprentice: {
        name: "Ученик",
        description: "Первое испытание. Тот же набор простых элементов, но доступно всего 6 тестов.",
        uses: 6,
        elementPool: EASY_ELEMENTS,
    },
    technician: {
        name: "Лаборант",
        description: "Новые горизонты. Расширенный список элементов (до Ксенона) и снова безлимитные тесты.",
        uses: 999,
        elementPool: MEDIUM_ELEMENTS,
    },
    analyst: {
        name: "Аналитик",
        description: "Работа под давлением. Знакомый расширенный список элементов, но всего 6 тестов на всё.",
        uses: 6,
        elementPool: MEDIUM_ELEMENTS,
    },
    chemist: {
        name: "Химик",
        description: "Сложные соединения. Почти все стабильные элементы (до Урана) и неограниченные тесты.",
        uses: 999,
        elementPool: HARD_ELEMENTS,
    },
    professor: {
        name: "Профессор",
        description: "Мастерство дедукции. Тот же сложный набор элементов, но всего 6 тестов.",
        uses: 6,
        elementPool: HARD_ELEMENTS,
    },
    expert: {
        name: "Эксперт",
        description: "На грани науки. Все 118 элементов доступны для изучения. Тесты не ограничены.",
        uses: 999,
        elementPool: EXPERT_ELEMENTS,
    },
    legend: {
        name: "Легенда",
        description: "Абсолютный вызов. Все 118 элементов и всего 6 тестов. Без права на ошибку.",
        uses: 6,
        elementPool: EXPERT_ELEMENTS,
    }
};